FROM fedora:latest

RUN groupadd -r builder -g 433 && \
    useradd -m -d /source -u 431 -r -g builder -s /sbin/nologin -c "Container build user" builder

USER root

RUN dnf group install 'Development Tools' -y && \
    dnf install vim nano wget curl automake bison cmake gettext-devel ldc meson ninja-build texinfo -y

USER builder

COPY . /source